// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include "anvl_types.h"
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// impl_dispatcher_create
Rcpp::XPtr<anvl::Dispatcher> impl_dispatcher_create(int capacity, SEXP compile_fn, Rcpp::Nullable<Rcpp::CharacterVector> static_names, std::string engine, std::string backend, bool move_inputs, SEXP default_device_fn, SEXP extractor_fn);
RcppExport SEXP _anvl_impl_dispatcher_create(SEXP capacitySEXP, SEXP compile_fnSEXP, SEXP static_namesSEXP, SEXP engineSEXP, SEXP backendSEXP, SEXP move_inputsSEXP, SEXP default_device_fnSEXP, SEXP extractor_fnSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type capacity(capacitySEXP);
    Rcpp::traits::input_parameter< SEXP >::type compile_fn(compile_fnSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::CharacterVector> >::type static_names(static_namesSEXP);
    Rcpp::traits::input_parameter< std::string >::type engine(engineSEXP);
    Rcpp::traits::input_parameter< std::string >::type backend(backendSEXP);
    Rcpp::traits::input_parameter< bool >::type move_inputs(move_inputsSEXP);
    Rcpp::traits::input_parameter< SEXP >::type default_device_fn(default_device_fnSEXP);
    Rcpp::traits::input_parameter< SEXP >::type extractor_fn(extractor_fnSEXP);
    rcpp_result_gen = Rcpp::wrap(impl_dispatcher_create(capacity, compile_fn, static_names, engine, backend, move_inputs, default_device_fn, extractor_fn));
    return rcpp_result_gen;
END_RCPP
}
// impl_dispatcher_size
int impl_dispatcher_size(SEXP dispatcher);
RcppExport SEXP _anvl_impl_dispatcher_size(SEXP dispatcherSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type dispatcher(dispatcherSEXP);
    rcpp_result_gen = Rcpp::wrap(impl_dispatcher_size(dispatcher));
    return rcpp_result_gen;
END_RCPP
}
// impl_dispatch_run
SEXP impl_dispatch_run(SEXP dispatcher, Rcpp::List args);
RcppExport SEXP _anvl_impl_dispatch_run(SEXP dispatcherSEXP, SEXP argsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type dispatcher(dispatcherSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type args(argsSEXP);
    rcpp_result_gen = Rcpp::wrap(impl_dispatch_run(dispatcher, args));
    return rcpp_result_gen;
END_RCPP
}
// impl_pjrt_api_versions
Rcpp::IntegerVector impl_pjrt_api_versions();
RcppExport SEXP _anvl_impl_pjrt_api_versions() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(impl_pjrt_api_versions());
    return rcpp_result_gen;
END_RCPP
}
// impl_tree_build
SEXP impl_tree_build(SEXP x);
RcppExport SEXP _anvl_impl_tree_build(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(impl_tree_build(x));
    return rcpp_result_gen;
END_RCPP
}
// impl_tree_build_flatten
Rcpp::List impl_tree_build_flatten(SEXP x);
RcppExport SEXP _anvl_impl_tree_build_flatten(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(impl_tree_build_flatten(x));
    return rcpp_result_gen;
END_RCPP
}
// impl_tree_unflatten
SEXP impl_tree_unflatten(SEXP tree, Rcpp::List x);
RcppExport SEXP _anvl_impl_tree_unflatten(SEXP treeSEXP, SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type tree(treeSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(impl_tree_unflatten(tree, x));
    return rcpp_result_gen;
END_RCPP
}
// impl_tree_size
int impl_tree_size(SEXP tree);
RcppExport SEXP _anvl_impl_tree_size(SEXP treeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type tree(treeSEXP);
    rcpp_result_gen = Rcpp::wrap(impl_tree_size(tree));
    return rcpp_result_gen;
END_RCPP
}
// impl_tree_equal
bool impl_tree_equal(SEXP a, SEXP b);
RcppExport SEXP _anvl_impl_tree_equal(SEXP aSEXP, SEXP bSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type a(aSEXP);
    Rcpp::traits::input_parameter< SEXP >::type b(bSEXP);
    rcpp_result_gen = Rcpp::wrap(impl_tree_equal(a, b));
    return rcpp_result_gen;
END_RCPP
}
// impl_tree_hash
std::string impl_tree_hash(SEXP tree);
RcppExport SEXP _anvl_impl_tree_hash(SEXP treeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type tree(treeSEXP);
    rcpp_result_gen = Rcpp::wrap(impl_tree_hash(tree));
    return rcpp_result_gen;
END_RCPP
}
// impl_tree_kind
std::string impl_tree_kind(SEXP tree);
RcppExport SEXP _anvl_impl_tree_kind(SEXP treeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type tree(treeSEXP);
    rcpp_result_gen = Rcpp::wrap(impl_tree_kind(tree));
    return rcpp_result_gen;
END_RCPP
}
// impl_tree_child_names
SEXP impl_tree_child_names(SEXP tree);
RcppExport SEXP _anvl_impl_tree_child_names(SEXP treeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type tree(treeSEXP);
    rcpp_result_gen = Rcpp::wrap(impl_tree_child_names(tree));
    return rcpp_result_gen;
END_RCPP
}
// impl_tree_child_kinds
Rcpp::CharacterVector impl_tree_child_kinds(SEXP tree);
RcppExport SEXP _anvl_impl_tree_child_kinds(SEXP treeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type tree(treeSEXP);
    rcpp_result_gen = Rcpp::wrap(impl_tree_child_kinds(tree));
    return rcpp_result_gen;
END_RCPP
}
// impl_tree_child_sizes
Rcpp::IntegerVector impl_tree_child_sizes(SEXP tree);
RcppExport SEXP _anvl_impl_tree_child_sizes(SEXP treeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type tree(treeSEXP);
    rcpp_result_gen = Rcpp::wrap(impl_tree_child_sizes(tree));
    return rcpp_result_gen;
END_RCPP
}
// impl_tree_path
std::string impl_tree_path(SEXP tree, int i);
RcppExport SEXP _anvl_impl_tree_path(SEXP treeSEXP, SEXP iSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type tree(treeSEXP);
    Rcpp::traits::input_parameter< int >::type i(iSEXP);
    rcpp_result_gen = Rcpp::wrap(impl_tree_path(tree, i));
    return rcpp_result_gen;
END_RCPP
}
// impl_tree_filter_by_names
SEXP impl_tree_filter_by_names(SEXP tree, Rcpp::CharacterVector names);
RcppExport SEXP _anvl_impl_tree_filter_by_names(SEXP treeSEXP, SEXP namesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type tree(treeSEXP);
    Rcpp::traits::input_parameter< Rcpp::CharacterVector >::type names(namesSEXP);
    rcpp_result_gen = Rcpp::wrap(impl_tree_filter_by_names(tree, names));
    return rcpp_result_gen;
END_RCPP
}
// impl_tree_concat
SEXP impl_tree_concat(Rcpp::List children, SEXP names);
RcppExport SEXP _anvl_impl_tree_concat(SEXP childrenSEXP, SEXP namesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List >::type children(childrenSEXP);
    Rcpp::traits::input_parameter< SEXP >::type names(namesSEXP);
    rcpp_result_gen = Rcpp::wrap(impl_tree_concat(children, names));
    return rcpp_result_gen;
END_RCPP
}
// impl_tree_mask_from_names
Rcpp::LogicalVector impl_tree_mask_from_names(SEXP tree, Rcpp::CharacterVector names);
RcppExport SEXP _anvl_impl_tree_mask_from_names(SEXP treeSEXP, SEXP namesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type tree(treeSEXP);
    Rcpp::traits::input_parameter< Rcpp::CharacterVector >::type names(namesSEXP);
    rcpp_result_gen = Rcpp::wrap(impl_tree_mask_from_names(tree, names));
    return rcpp_result_gen;
END_RCPP
}
// impl_tree_repr
std::string impl_tree_repr(SEXP tree);
RcppExport SEXP _anvl_impl_tree_repr(SEXP treeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type tree(treeSEXP);
    rcpp_result_gen = Rcpp::wrap(impl_tree_repr(tree));
    return rcpp_result_gen;
END_RCPP
}
// impl_tree_diff
SEXP impl_tree_diff(SEXP a, SEXP b);
RcppExport SEXP _anvl_impl_tree_diff(SEXP aSEXP, SEXP bSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type a(aSEXP);
    Rcpp::traits::input_parameter< SEXP >::type b(bSEXP);
    rcpp_result_gen = Rcpp::wrap(impl_tree_diff(a, b));
    return rcpp_result_gen;
END_RCPP
}

RcppExport SEXP run_testthat_tests(SEXP);

static const R_CallMethodDef CallEntries[] = {
    {"_anvl_impl_dispatcher_create", (DL_FUNC) &_anvl_impl_dispatcher_create, 8},
    {"_anvl_impl_dispatcher_size", (DL_FUNC) &_anvl_impl_dispatcher_size, 1},
    {"_anvl_impl_dispatch_run", (DL_FUNC) &_anvl_impl_dispatch_run, 2},
    {"_anvl_impl_pjrt_api_versions", (DL_FUNC) &_anvl_impl_pjrt_api_versions, 0},
    {"_anvl_impl_tree_build", (DL_FUNC) &_anvl_impl_tree_build, 1},
    {"_anvl_impl_tree_build_flatten", (DL_FUNC) &_anvl_impl_tree_build_flatten, 1},
    {"_anvl_impl_tree_unflatten", (DL_FUNC) &_anvl_impl_tree_unflatten, 2},
    {"_anvl_impl_tree_size", (DL_FUNC) &_anvl_impl_tree_size, 1},
    {"_anvl_impl_tree_equal", (DL_FUNC) &_anvl_impl_tree_equal, 2},
    {"_anvl_impl_tree_hash", (DL_FUNC) &_anvl_impl_tree_hash, 1},
    {"_anvl_impl_tree_kind", (DL_FUNC) &_anvl_impl_tree_kind, 1},
    {"_anvl_impl_tree_child_names", (DL_FUNC) &_anvl_impl_tree_child_names, 1},
    {"_anvl_impl_tree_child_kinds", (DL_FUNC) &_anvl_impl_tree_child_kinds, 1},
    {"_anvl_impl_tree_child_sizes", (DL_FUNC) &_anvl_impl_tree_child_sizes, 1},
    {"_anvl_impl_tree_path", (DL_FUNC) &_anvl_impl_tree_path, 2},
    {"_anvl_impl_tree_filter_by_names", (DL_FUNC) &_anvl_impl_tree_filter_by_names, 2},
    {"_anvl_impl_tree_concat", (DL_FUNC) &_anvl_impl_tree_concat, 2},
    {"_anvl_impl_tree_mask_from_names", (DL_FUNC) &_anvl_impl_tree_mask_from_names, 2},
    {"_anvl_impl_tree_repr", (DL_FUNC) &_anvl_impl_tree_repr, 1},
    {"_anvl_impl_tree_diff", (DL_FUNC) &_anvl_impl_tree_diff, 2},
    {"run_testthat_tests", (DL_FUNC) &run_testthat_tests, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_anvl(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
