# Generated by anvl::jit_roclet: do not edit by hand

# Functions tagged with `#' @jit` are rebound at package build time to
# `jit(f, backend = "auto", static = <static>)`. See R/jit-roclet.R.

.jit_registry <- list(
  list(name = "nv_add", static = character(0))
)
