# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

impl_dispatcher_create <- function(capacity, compile_fn, static_names, engine, backend, move_inputs, default_device_fn, extractor_fn) {
    .Call(`_anvl_impl_dispatcher_create`, capacity, compile_fn, static_names, engine, backend, move_inputs, default_device_fn, extractor_fn)
}

impl_dispatcher_size <- function(dispatcher) {
    .Call(`_anvl_impl_dispatcher_size`, dispatcher)
}

impl_dispatch_run <- function(dispatcher, args) {
    .Call(`_anvl_impl_dispatch_run`, dispatcher, args)
}

impl_pjrt_api_versions <- function() {
    .Call(`_anvl_impl_pjrt_api_versions`)
}

impl_tree_build <- function(x) {
    .Call(`_anvl_impl_tree_build`, x)
}

impl_tree_build_flatten <- function(x) {
    .Call(`_anvl_impl_tree_build_flatten`, x)
}

impl_tree_unflatten <- function(tree, x) {
    .Call(`_anvl_impl_tree_unflatten`, tree, x)
}

impl_tree_size <- function(tree) {
    .Call(`_anvl_impl_tree_size`, tree)
}

impl_tree_equal <- function(a, b) {
    .Call(`_anvl_impl_tree_equal`, a, b)
}

impl_tree_hash <- function(tree) {
    .Call(`_anvl_impl_tree_hash`, tree)
}

impl_tree_kind <- function(tree) {
    .Call(`_anvl_impl_tree_kind`, tree)
}

impl_tree_child_names <- function(tree) {
    .Call(`_anvl_impl_tree_child_names`, tree)
}

impl_tree_child_kinds <- function(tree) {
    .Call(`_anvl_impl_tree_child_kinds`, tree)
}

impl_tree_child_sizes <- function(tree) {
    .Call(`_anvl_impl_tree_child_sizes`, tree)
}

impl_tree_path <- function(tree, i) {
    .Call(`_anvl_impl_tree_path`, tree, i)
}

impl_tree_filter_by_names <- function(tree, names) {
    .Call(`_anvl_impl_tree_filter_by_names`, tree, names)
}

impl_tree_concat <- function(children, names) {
    .Call(`_anvl_impl_tree_concat`, children, names)
}

impl_tree_mask_from_names <- function(tree, names) {
    .Call(`_anvl_impl_tree_mask_from_names`, tree, names)
}

impl_tree_repr <- function(tree) {
    .Call(`_anvl_impl_tree_repr`, tree)
}

impl_tree_diff <- function(a, b) {
    .Call(`_anvl_impl_tree_diff`, a, b)
}

